PARSER_BEGIN(SyntaxChecker)

public class SyntaxChecker {
    public static void main(String[] args) {
        try {
            new SyntaxChecker(new java.io.StringReader(args[0])).S();
            System.out.println("Syntax is okay");
        } catch (Throwable e) {
            // Catching Throwable is ugly but JavaCC throws Error objects!
            System.out.println("Syntax check failed: " + e.getMessage());
        }
    }
}

PARSER_END(SyntaxChecker)

SKIP:  { " " | "\t" | "\n" | "\r"  | "\\"  }
TOKEN: {
  < INC_V:	"+" > {System.out.println("Increasing the value");}
| < DEC_V:	"-" > {System.out.println("Decreasing the value");}
| < INC_P:	">" > {System.out.println("Increasing the pointer");}
| < DEC_P:	"<" > {System.out.println("Decreasing the pointer");}
| < OUT:	"." > {System.out.println("Outputing");}
| < INP:	"," > {System.out.println("Inputting");}
| < LOOP_B:	"[" > {System.out.println("Loop begins");}
| < LOOP_E:	"]" > {System.out.println("Loop ends");}

}

void S(): {} { (MatchedBraces())* <EOF> }

void MatchedBraces() :{}
{
  (<LOOP_B> [ MatchedBraces() ] <LOOP_E>)+
}
